### ISSUE TITLE
Kombinatorik erweitern

### ISSUE THREAD

**Issue by timsch4fer** [g4bri3lDev/dsscripts#32]

**Comment by B14CK313** [comment]
Ich versuche heute noch die Goldene Tablle umzusetzen, damit man nur noch anhaken muss, was unterscheidbar ist, welchen Typ man braucht und es direkt Rechenweg+Ergebnis ausspuckt

**Comment by GeneralMine** [comment]
durch all in one implementiert, das Issue kann man closen
