### ISSUE TITLE
Special Symbols register

### ISSUE THREAD

**Issue by timsch4fer** [g4bri3lDev/dsscripts#34]
A Register with important symbols for DS
- Σ, ∈, ∉ etc

**Comment by GeneralMine** [comment]
In my lecture notes I also got these symbols:
Δ
∈
∉
∅
∪
∩
∖
¯
⊆
⊄
⊊
Alphabet: Σ oder Γ
Empty Word: ε oder λ

**Comment by GeneralMine** [comment]
implemented with pull request.
Feel free to add more symbols!

**Comment by GeneralMine** [comment]
@g4bri3lDev closable
