### ISSUE TITLE
KV map custom label

### ISSUE THREAD

**Issue by MrMoreFett** [g4bri3lDev/dsscripts#72]
Da Luttis Gang gerne mal die Label an den KV Diagrammen vertauscht/ändert, wäre es sinnvoll, wenn man die Bezeichnungen selbst eingeben kann. Die eingegebenen Bezeichnungen sollten dann bei der KNF/DNF beachtet werden. https://i.imgur.com/QsFWwF0.png

**Comment by GeneralMine** [comment]
Danke für den Vorschlag! Hab ich hier implementiert: #76
